/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.skladiste.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import hr.edunova.skladiste.controller.ObradaNarudzba;
import hr.edunova.skladiste.controller.ObradaProizvod;
import hr.edunova.skladiste.controller.ObradaZaposlenik;
import hr.edunova.skladiste.model.Narudzba;
import hr.edunova.skladiste.model.Proizvod;
import hr.edunova.skladiste.model.ProizvodNarudzba;
import hr.edunova.skladiste.model.Zaposlenik;
import hr.edunova.skladiste.util.EdunovaException; 
import hr.edunova.skladiste.util.Pomocno;
import java.util.Locale;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author marko
 */
public class ViewNarudzba extends javax.swing.JFrame {

    private final ObradaNarudzba obrada;
    private final ObradaProizvod obradaProizvod;
    
    /**
     * Creates new form ViewNarudzba
     */
    public ViewNarudzba() {
        initComponents();
        obrada = new ObradaNarudzba();
        obradaProizvod = new ObradaProizvod();
        ucitajZaposlenike();
        ucitaj();
        obrada.setEntitet(new Narudzba());
        DatePickerSettings dps = new DatePickerSettings(new Locale("hr","HR"));
        dps.setFormatForDatesCommonEra("dd.MM.yyyy.");
        dpDatum.setSettings(dps);
    }

    private void ucitajZaposlenike(){
        DefaultComboBoxModel<Zaposlenik> m = new DefaultComboBoxModel<>();
        new ObradaZaposlenik().getPodaci().forEach(s->m.addElement(s));
        cmbZaposlenik.setModel(m);
    }
    
    private void ucitaj() {
        DefaultListModel<Narudzba> g = new DefaultListModel<>();
        obrada.getPodaci().forEach(s->g.addElement(s));
        lstPodaci.setModel(g);
    }
    
    private void ucitajVrijednosti() {
        obrada.getEntitet().setSifra(Integer.parseInt(txtSifra.getText()));
        obrada.getEntitet().setZaposlenik(cmbZaposlenik.getModel().getElementAt(cmbZaposlenik.getSelectedIndex()));
        if(dpDatum.getDate()!=null){
            Date d = Pomocno.convertToDateViaInstant(dpDatum.getDate());
            obrada.getEntitet().setDatum(d);
        }
        
        try {
            DefaultListModel<ProizvodNarudzba> m = (DefaultListModel<ProizvodNarudzba>)lstProizvodiUNarudzbi.getModel();
            obrada.ocistiProizvodeUNarudzbi();
            for(int i=0;i<m.getSize();i++){
                obrada.getEntitet().getStavke().add(m.get(i));
            }
        } catch (Exception e) {
        }
        
    }
    
    private void postaviVrijednosti(){
        txtSifra.setText(Pomocno.getFormatCijelogBroja(obrada.getEntitet().getSifra()));
        if(obrada.getEntitet().getDatum()==null){
            dpDatum.setDate(null);
        }else{
            dpDatum.setDate(Pomocno.convertToLocalDateViaInstant(obrada.getEntitet().getDatum()));
        }
        postaviZaposlenike();
        postaviProizvode();
    }
    
    private void postaviZaposlenike(){
        for(int i=0;i<cmbZaposlenik.getModel().getSize();i++){
            if(cmbZaposlenik.getModel().getElementAt(i).getId().equals(obrada.getEntitet().getZaposlenik().getId())){
                cmbZaposlenik.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void postaviProizvode(){
        DefaultListModel<ProizvodNarudzba> m = new DefaultListModel<>();
        obrada.getEntitet().getStavke().forEach(c->{m.addElement(c);});
        lstProizvodiUNarudzbi.setModel(m);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPodaci = new javax.swing.JList<>();
        cmbZaposlenik = new javax.swing.JComboBox<>();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProizvodiUNarudzbi = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstProizvodi = new javax.swing.JList<>();
        btnTrazi = new javax.swing.JButton();
        txtUvjet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dpDatum = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstPodaci.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPodaciValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPodaci);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lstProizvodiUNarudzbi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProizvodiUNarudzbiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstProizvodiUNarudzbi);

        jLabel2.setText("Proizvodi u narudzbi");

        lstProizvodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProizvodiMouseClicked(evt);
            }
        });
        lstProizvodi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProizvodiValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstProizvodi);

        btnTrazi.setText("Traži");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });

        txtUvjet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUvjetKeyPressed(evt);
            }
        });

        jLabel3.setText("Šifra");

        txtSifra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSifraMouseClicked(evt);
            }
        });
        txtSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraActionPerformed(evt);
            }
        });

        jLabel4.setText("Datum");

        jLabel5.setText("Zaposlenik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbZaposlenik, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromjeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSifra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(dpDatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtUvjet, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(dpDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addComponent(cmbZaposlenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnPromjeni)
                            .addComponent(btnObrisi))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTrazi))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
        ucitajProizvode();
    }//GEN-LAST:event_btnTraziActionPerformed

    private void txtUvjetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUvjetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ucitajProizvode();
        }
    }//GEN-LAST:event_txtUvjetKeyPressed

    private void lstPodaciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPodaciValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }
        obrada.setEntitet(lstPodaci.getSelectedValue());
        if (obrada.getEntitet() == null) {
            return;
        }
        postaviVrijednosti();
    }//GEN-LAST:event_lstPodaciValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try {
            
            ucitajVrijednosti();
            obrada.create();
            ucitaj();
        } catch (EdunovaException ex) {
            JOptionPane.showMessageDialog(null, ex.getPoruka());
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        if (obrada.getEntitet() == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite stavku");
            return;
        }
        
        ucitajVrijednosti();
        try {
            obrada.update();
            ucitaj();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(null, e.getPoruka());
        }
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if (obrada.getEntitet() == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite stavku");
            return;
        }
        try {
            obrada.delete();
            ucitaj();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(null, e.getPoruka());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void lstProizvodiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProizvodiValueChanged
        
    }//GEN-LAST:event_lstProizvodiValueChanged

    private void lstProizvodiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProizvodiMouseClicked
        if (evt.getClickCount() == 2) {
            int index = lstProizvodi.locationToIndex(evt.getPoint());
            Proizvod p = lstProizvodi.getModel().getElementAt(index);
            
            try {
                DefaultListModel<ProizvodNarudzba> m = (DefaultListModel<ProizvodNarudzba>) lstProizvodiUNarudzbi.getModel();
              for(int i=0;i<m.getSize();i++){
                  if(m.get(i).getProizvod().getId().equals(p.getId())){
                      return;
                  }
              } 
            } catch (Exception e) {
            }
             
            
    
            obradaProizvod.setEntitet(p);
            ProizvodNarudzba pn = new ProizvodNarudzba();
            pn.setProizvod(p);
            pn.setNarudzba(obrada.getEntitet());
            pn.setCijena(obradaProizvod.cijenaNakonPdva(obradaProizvod.getEntitet().getCijena()));
            DefaultListModel<ProizvodNarudzba> m;
            
            try {
                m = (DefaultListModel<ProizvodNarudzba>) lstProizvodiUNarudzbi.getModel();
            } catch (Exception e) {
                m = new DefaultListModel<>();
                lstProizvodiUNarudzbi.setModel(m);
            }
            
            m.addElement(pn);
            lstProizvodiUNarudzbi.repaint();
            
        }
    }//GEN-LAST:event_lstProizvodiMouseClicked

    private void lstProizvodiUNarudzbiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProizvodiUNarudzbiMouseClicked
        if(evt.getClickCount() == 2) {
            int index = lstProizvodiUNarudzbi.locationToIndex(evt.getPoint());
            
            DefaultListModel<ProizvodNarudzba> m = (DefaultListModel<ProizvodNarudzba>) lstProizvodiUNarudzbi.getModel();
            m.remove(index);
            
            lstProizvodiUNarudzbi.repaint();
            
        }
    }//GEN-LAST:event_lstProizvodiUNarudzbiMouseClicked

    private void txtSifraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSifraMouseClicked
        
        System.out.println(obrada.Sifra());
         
        txtSifra.setText(obrada.Sifra().toString());
      
      
    }//GEN-LAST:event_txtSifraMouseClicked

    private void txtSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JComboBox<Zaposlenik> cmbZaposlenik;
    private com.github.lgooddatepicker.components.DatePicker dpDatum;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Narudzba> lstPodaci;
    private javax.swing.JList<Proizvod> lstProizvodi;
    private javax.swing.JList<ProizvodNarudzba> lstProizvodiUNarudzbi;
    private javax.swing.JTextField txtSifra;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables

    
    private void ucitajProizvode(){
        DefaultListModel<Proizvod> m = new DefaultListModel<>();
        obradaProizvod.getPodaci(txtUvjet.getText().trim()).forEach(s -> m.addElement(s));
        lstProizvodi.setModel(m);
    }

}
// sifru naci zadnju u bazi order by desc i to plus jedan predloziti korisniku, dodati textfield i gumb na view